[0;34m[2025-07-06 08:02:16][0m Limpando cache de m√≥dulos Python...
[0;32m[2025-07-06 08:02:16] ‚úÖ SUCESSO: Cache de m√≥dulos limpo.[0m
[0;34m[2025-07-06 08:02:16][0m Ativando ambiente virtual...
[0;32m[2025-07-06 08:02:16] ‚úÖ SUCESSO: Ambiente virtual ativado.[0m
[0;34m[2025-07-06 08:02:16][0m Verificando conex√£o com Redis (localhost:6379)...
[0;32m[2025-07-06 08:02:16] ‚úÖ SUCESSO: Redis dispon√≠vel e respondendo.[0m
[0;34m[2025-07-06 08:02:16][0m Mudando para o diret√≥rio do projeto: /home/ubuntu/superbot...
[0;32m[2025-07-06 08:02:16] ‚úÖ SUCESSO: Diret√≥rio do projeto acessado.[0m
[0;34m[2025-07-06 08:02:16][0m Verificando workers antigos para parar...
[0;34m[2025-07-06 08:02:16][0m Nenhum worker antigo encontrado. Prosseguindo...
[0;34m[2025-07-06 08:02:16][0m ‚öôÔ∏è Iniciando worker: worker-3
[0;34m[2025-07-06 08:02:16][0m üìã Logs ser√£o salvos em: logs/worker_3.log
<frozen runpy>:128: RuntimeWarning: 'rq.worker' found in sys.modules after import of package 'rq', but prior to execution of 'rq.worker'; this may result in unpredictable behaviour
[0;31m[2025-07-06 08:02:18] ‚ùå ERRO: Falha ao iniciar o worker. Verifique os logs em logs/worker_3.log[0m
